export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const UPDATE_DELETE = 'UPDATE_DELETE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_FORM = 'ADD_FORM';
